version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/TimePlanning.Pn/TimePlanning.Pn"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/TimePlanning.Pn/TimePlanning.Pn.Test"
  schedule:
    interval: daily